name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request_review:
    types: [submitted]
    
permissions:
  contents: write
  issues: write
  pull-requests: write
    
jobs:
  claude-response:
    if: github.actor != 'sourcery-ai[bot]' && github.actor != 'another-bot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # trigger_phrase: "/claude"
          # assignee_trigger: "claude"
          # label_trigger: "claude"
          # claude_env: |
          #   NODE_ENV: test
          #   DEBUG: true
          #   API_URL: https://api.example.com
          # max_turns: "5"
          # additional_permissions: |
          #   actions: read
